config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :members, :except => [:index] do
    collection do
      match "login", :to => "members#login", :via => :all
      get :logout
      get :profile
    end

    resources :skills, :only => [:index], :controller => "member/skills" do
      member do
        get :select
        get :deselect
      end
    end
  end

  resources :skills
  resources :ministries

  get "/admin" => 'admin#index'

  root :to => redirect('/members/profile')
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :parent, :class_name => "Skill", :required => false
  has_many :children, :foreign_key => :parent_id, :class_name => "Skill"

  has_many :ministry_skills
  has_many :ministries, :through => :ministry_skills

  has_many :member_skills
  has_many :members, :through => :member_skills

  scope :ordered, -> { order(:title => :desc) }
  scope :top_level, -> { ordered.where(:parent_id => nil) }

  before_save :update_slug

  def self.create_from_params(params)
    skill = self.find_or_initialize_by(title: params[:title])
    skill.update_from_params(params)
    skill
  end

  def update_from_params(params)
    update(params)
  end

  def to_param
    self.slug
  end

  def top_level?
    parent_id.nil?
  end

  def leaf?
    children.none?
  end

  def has_ancestor?(ancestor, include_self=false)
    ancestor_skills(include_self).include?(ancestor)
  end

  def ancestor_skills(include_self=false)
    skills = Array(parent.try(:ancestor_skills, true))
    if include_self
      skills << self
    end
    skills.compact
  end

  def descendent_skills(include_self=false)
    skills =
      if include_self
        [self]
      else
        []
      end
    skills.concat(children.flat_map { |child| child.descendent_skills(true) }).compact
  end

  private

  def update_slug
    self.slug = title.parameterize
  end
end

app/controllers/member/skills_controller.rb
# module Member; end

class Member::SkillsController < ApplicationController
  before_filter :load_skills

  def index
  end

  def select
    if @selected_skill
      current_member.select_skill(@selected_skill)
    end
    render "index"
  end

  def deselect
    if @selected_skill
      current_member.deselect_skill(@selected_skill)
    end
    render "index"
  end

  private

  def load_skills
    @skills = Skill.top_level
    @selected_skill = Skill.find_by_slug(params[:id])
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_filter :load_skill, :only => [:show, :edit, :update]

  def index
    @skills = Skill.ordered
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.create_from_params(skill_params)
    if @skill.valid?
      redirect_to skill_path(@skill)
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @skill.update_from_params(skill_params)
    if @skill.valid?
      redirect_to skill_path(@skill)
    else
      render "edit"
    end
  end

  private

  def load_skill
    @skill = Skill.find_by_slug(params[:id])
    raise_not_found unless @skill
  end

  def skill_params
    params
      .require(:skill).permit(:title, :member_description, :ministry_description, :shared_description)
      .to_h
      .symbolize_keys
  end
end

app/views/skills/edit.html.slim
- content_for(:title, t(".title", :title => @skill.title))
.row
  .large-12.columns
    nav.navigation
      ul.breadcrumbs
        li = link_to t("skills.index.title"), skills_path
        li = title
    h1 = title
    = simple_form_for @skill do |f|
      .row
        .large-12.columns
          = f.input :title, :required => true
      .row
        .large-12.columns
          = f.input :member_description
      .row
        .large-12.columns
          = f.input :ministry_description
      .row
        .large-12.columns
          = f.input :shared_description
      .row
        .large-12.columns
          = link_to t(".cancel"), skills_path, :class => "button secondary float-left"
          = f.button :submit, :value => t(".submit"), :class => "float-right"

app/views/skills/index.html.slim
.row
  .large-12.columns
    h1 = title
    .row
      .large-12.columns
        = link_to t(".new"), new_skill_path
    - if @skills.present?
      .row
        .large-12.columns
          table
            tbody
              - @skills.each do |skill|
                tr
                  td
                    = link_to skill.title, skill_path(skill)
                  td
                    = link_to t(".edit"), edit_skill_path(skill)

app/views/skills/new.html.slim
.row
  .large-12.columns
    nav.navigation
      ul.breadcrumbs
        li = link_to t("skills.index.title"), skills_path
        li = title
    h1 = title
    = simple_form_for @skill do |f|
      .row
        .large-12.columns
          = f.input :title, :required => true
      .row
        .large-12.columns
          = f.input :member_description
      .row
        .large-12.columns
          = f.input :ministry_description
      .row
        .large-12.columns
          = f.input :shared_description
      .row
        .large-12.columns
          = link_to t(".cancel"), skills_path, :class => "button secondary float-left"
          = f.button :submit, :value => t(".submit"), :class => "float-right"

app/views/skills/show.html.slim
- content_for(:title, t(".title", :title => @skill.title))
.row
  .large-12.columns
    nav.navigation
      ul.breadcrumbs
        li = link_to t("skills.index.title"), skills_path
        li = title
    h1 = title
    hr
    .row
      .large-12.columns
        h3 = t(".ministry_description")
        p = @skill.ministry_description
    .row
      .large-12.columns
        h3 = t(".member_description")
        p = @skill.member_description
    hr
    .row
      .large-12.columns
        = link_to t(".edit"), edit_skill_path(@skill), :class => "button"