config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :members, :except => [:index] do
    collection do
      match "login", :to => "members#login", :via => :all
      get :logout
      get :profile
    end

    resources :skills, :only => [:index], :controller => "member/skills" do
      member do
        get :select
        get :deselect
      end
    end
  end

  resources :skills
  resources :ministries

  get "/admin" => 'admin#index'

  root :to => redirect('/members/profile')
end

app/views/shared/_header.html.slim
.top-bar
  .top-bar-title
    span data-responsive-toggle="responsive-menu" data-hide-for="medium"
      span class="menu-icon dark" data-toggle=true
    = link_to root_path do
      strong Skill Matcher
  #responsive-menu
    .top-bar-right
      ul.menu.vertical.medium-horizontal data-responsive-menu="drilldown medium-dropdown"
        - if current_member.blank?
          li
            = link_to t(".login"), login_members_path
          li
            = link_to t(".create_account"), new_member_path
        - else
          li
            = link_to t(".me"), profile_members_path
            ul.menu.vertical
              li
                = link_to t(".profile"), profile_members_path
              li
                = link_to t(".my_skills"), member_skills_path(current_member)
          - if current_member.possible_admin?
            li
              = link_to t(".admin")
              ul.menu.vertical
                li
                  = link_to t(".skills"), skills_path
                li
                  = link_to t(".ministries"), ministries_path
          li
            = link_to t(".logout"), logout_members_path