config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :members, :except => [:index] do
    collection do
      match "login", :to => "members#login", :via => :all
      get :logout
      get :profile
    end

    resources :skills, :only => [:index], :controller => "member/skills" do
      member do
        get :select
        get :deselect
      end
    end
  end

  resources :skills
  resources :ministries

  get "/admin" => 'admin#index'

  root :to => redirect('/members/profile')
end

app/models/ministry.rb
class Ministry < ApplicationRecord
  has_many :ministry_skills
  has_many :skills, :through => :ministry_skills
  has_many :member_skills, :through => :skills
  has_many :members, :through => :member_skills

  scope :ordered, -> { order(:name => :desc) }

  before_save :update_slug

  def self.create_from_params(params)
    ministry = self.find_or_initialize_by(name: params[:name])
    ministry.update_from_params(params)
    ministry
  end

  def update_from_params(params)
    update(params)
  end

  def to_param
    self.slug
  end

  private

  def update_slug
    self.slug = self.name.parameterize
  end
end

app/controllers/ministries_controller.rb
class MinistriesController < ApplicationController
  before_filter :load_ministry, :only => [:show, :edit, :update]

  def index
    @ministries = Ministry.ordered
  end

  def new
    @ministry = Ministry.new
  end

  def create
    @ministry = Ministry.create_from_params(ministry_params)
    if @ministry.valid?
      redirect_to ministry_path(@ministry)
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @ministry.update_from_params(ministry_params)
    if @ministry.valid?
      redirect_to ministry_path(@ministry)
    else
      render "edit"
    end
  end

  private

  def load_ministry
    @ministry = Ministry.find_by_slug(params[:id])
  end

  def ministry_params
    params
      .require(:ministry).permit(:name, :description)
      .to_h
      .symbolize_keys
  end
end

app/views/ministries/edit.html.slim
- content_for(:title, t(".title", :name => @ministry.name))
.row
  .large-12.columns
    nav.navigation
      ul.breadcrumbs
        li = link_to t("ministries.index.title"), ministries_path
        li = title
    h1 = title
    = simple_form_for @ministry do |f|
      .row
        .large-12.columns
          = f.input :name, :required => true
      .row
        .large-12.columns
          = f.input :description
      .row
        .large-12.columns
          = link_to t(".cancel"), ministries_path, :class => "button secondary float-left"
          = f.button :submit, :value => t(".submit"), :class => "float-right"

app/views/ministries/index.html.slim
.row
  .large-12.columns
    h1 = title
    .row
      .large-12.columns
        = link_to t(".new"), new_ministry_path
        - if @ministries.present?
      .row
        .large-12.columns
          table
            tbody
              - @ministries.each do |ministry|
                tr
                  td
                    = link_to ministry.name, ministry_path(ministry)
                  td
                    = link_to t(".edit"), edit_ministry_path(ministry)

app/views/ministries/new.html.slim
.row
  .large-12.columns
    nav.navigation
      ul.breadcrumbs
        li = link_to t("ministries.index.title"), ministries_path
        li = title
    h1 = title
    = simple_form_for @ministry do |f|
      .row
        .large-12.columns
          = f.input :name, :required => true
      .row
        .large-12.columns
          = f.input :description
      .row
        .large-12.columns
          = link_to t(".cancel"), ministries_path, :class => "button secondary float-left"
          = f.button :submit, :value => t(".submit"), :class => "float-right"

app/views/ministries/show.html.slim
- content_for(:title, t(".title", name: @ministry.name))
.row
  .large-12.columns
    nav.navigation
      ul.breadcrumbs
        li = link_to t("ministries.index.title"), ministries_path
        li = title
    h1 = title
    .row
      .large-12.columns
        p = @ministry.description
    .row
      .large-12.columns
        h3 = t(".skills")
        - @ministry.skills.each do |skill|
          .callout
            h4 = skill.title

    .row
      .large-12.columns
        = link_to t(".edit"), edit_ministry_path(@ministry), :class => "button"